name: sport_store_app
description: "sport store Mobile Application"
publish_to: none

version: 1.0.0+1

environment:
  sdk: '3.4.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  http: ^1.2.1
  intl: ^0.19.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/name1.png
    - assets/images/pass1.png
    - assets/images/user1.png
    - assets/images/football_shoes.png
    - assets/images/football_shoes2.png
    - assets/images/football_shoes3.png
    - assets/images/basketball_jersey.png
    - assets/images/basketball_jersey2.png
    - assets/images/basketball_jersey3.png
    - assets/images/tennis_racket.png
    - assets/images/tennis_racket2.png
    - assets/images/tennis_racket3.png
    - assets/images/running_shoes.png
    - assets/images/running_shoes2.png
    - assets/images/running_shoes3.png